language: ruby
# Just to override the --deployment default arg
bundler_args: --no-color
script: "bundle exec rake"

notifications:
  email:
    on_success: change
    on_failure: always

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-19mode

matrix:
  allow_failures:

