language: ruby
# Just to override the --deployment default arg
bundler_args: --no-color
script: "bundle exec rake"

notifications:
  email:
    on_success: change
    on_failure: always

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode

matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: jruby-19mode
    - rvm: rbx-19mode

