language: ruby
# Just to override the --deployment default arg
bundler_args: --no-color
script: "bundle exec rake"

notifications:
  email:
    on_success: change
    on_failure: always

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.0
  - jruby-19mode
  - rbx-2.2.6

matrix:
  allow_failures:

